version: '3'
services:
  web:
    working_dir: ${PWD}
    image: theia
    ports:
      - 80:80
      - 3000:3000
    environment:
      APACHE_DOCUMENT_ROOT: ${PWD}
      GIT_USER_NAME:
      GIT_USER_EMAIL:
      GITHUB_API_TOKEN:
      WAKATIME_API_KEY:
    volumes:
      - ${PWD}:${PWD}
      - ~/.ssh:/home/web/.ssh
