name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0]
    env:
      IMAGE_NAME: php-theia

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.php-version }} image
        run: docker build . --file Dockerfile --tag image --build-arg PHP_VERSION=${{ matrix.php-version }}

      - name: Log into registries
        run: |
          # Login to Dockerhub.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u verbral --password-stdin
          # Login to Github.
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin

      - name: Push ${{ matrix.php-version }} image to registries
        run: |
          # Push to Dockerhub.
          docker tag image docker.io/verbral/$IMAGE_NAME:${{ matrix.php-version }}
          docker push docker.io/verbral/$IMAGE_NAME:${{ matrix.php-version }}
          # Push to Github.
          docker tag image docker.pkg.github.com/verbruggenalex/docker-php-theia/$IMAGE_NAME:${{ matrix.php-version }}
          docker push docker.pkg.github.com/verbruggenalex/docker-php-theia/$IMAGE_NAME:${{ matrix.php-version }}

      - name: Sync Readme to Dockerhub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: verbral
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: verbral/php-theia
        if: matrix.php-version == '7.4'
