name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker-theia-php

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registries
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u verbral --password-stdin
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin


      - name: Push image to registries
        run: |
          docker tag image docker.pkg.github.com/verbruggenalex/docker-theia-php/docker-theia-php:latest
          docker push docker.pkg.github.com/verbruggenalex/docker-theia-php/docker-theia-php:latest

          docker tag image docker.io/verbral/docker-theia-php:latest
          docker push docker.io/verbral/docker-theia-php:latest
